<?php

/**
 * This file is part of the Phalcon API.
 *
 * (c) Phalcon Team <team@phalcon.io>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

declare(strict_types=1);

namespace Phalcon\Api\Domain\Infrastructure\Enums\Http;

use Phalcon\Api\Domain\Infrastructure\Enums\EnumsInterface;

/**
 * Enumeration for Http Codes. These are not only the regular HTTP codes
 * but also the ones generated by the application
 */
enum HttpCodesEnum: int implements EnumsInterface
{
    /**
     * Regular HTTP codes
     */
    case OK           = 200;
    case BadRequest   = 400;
    case NotFound     = 404;
    case Unauthorized = 401;

    /**
     * Application specific codes
     */
    case AppMalformedPayload                = 3400;
    case AppRecordsNotFound                 = 3401;
    case AppResourceNotFound                = 3402;
    case AppUnauthorized                    = 3403;
    case AppCannotConnectToDatabase         = 3404;
    case AppCannotCreateDatabaseRecord      = 3405;
    case AppCannotDeleteDatabaseRecord      = 3406;
    case AppCannotUpdateDatabaseRecord      = 3407;
    case AppIncorrectCredentials            = 3408;
    case AppInvalidArguments                = 3409;
    case AppTokenInvalidAudience            = 3410;
    case AppTokenInvalidCannotDecodeContent = 3411;
    case AppTokenInvalidIdentifier          = 3412;
    case AppTokenInvalidIssuer              = 3413;
    case AppTokenInvalidStructure           = 3414;
    case AppTokenInvalidTenant              = 3415;
    case AppTokenInvalidUser                = 3416;
    case AppTokenNotPresent                 = 3417;
    case AppTokenNotValid                   = 3418;
    case AppTokenSignatureNotValid          = 3419;
    case AppTokenUnsupportedHeaderFound     = 3420;
    case AppValidationFailed                = 3421;


    /**
     * Returns an array with the value as key and text as value
     *
     * @return array<integer,string>
     */
    public function error(): array
    {
        return [$this->value => $this->text()];
    }

    /**
     * Return the text associated with the option
     *
     * @return string
     */
    public function text(): string
    {
        return match ($this) {
            HttpCodesEnum::OK                                 => 'OK',
            HttpCodesEnum::BadRequest                         => 'Bad Request',
            HttpCodesEnum::NotFound                           => 'Not Found',
            HttpCodesEnum::AppMalformedPayload                => 'Malformed payload',
            HttpCodesEnum::AppRecordsNotFound                 => 'Record(s) not found',
            HttpCodesEnum::AppResourceNotFound                => 'Resource not found',
            HttpCodesEnum::Unauthorized,
            HttpCodesEnum::AppUnauthorized                    => 'Unauthorized',
            HttpCodesEnum::AppCannotConnectToDatabase         => 'Failure connecting to the database',
            HttpCodesEnum::AppCannotCreateDatabaseRecord      => 'Cannot create database record: ',
            HttpCodesEnum::AppCannotDeleteDatabaseRecord      => 'Cannot delete database record: ',
            HttpCodesEnum::AppCannotUpdateDatabaseRecord      => 'Cannot update database record: ',
            HttpCodesEnum::AppIncorrectCredentials            => 'Incorrect credentials',
            HttpCodesEnum::AppInvalidArguments                => 'Invalid arguments provided',
            HttpCodesEnum::AppTokenInvalidAudience            => 'Invalid Token [Audience]',
            HttpCodesEnum::AppTokenInvalidCannotDecodeContent => 'Invalid Token [Cannot decode content]',
            HttpCodesEnum::AppTokenInvalidIdentifier          => 'Invalid Token [Identifier]',
            HttpCodesEnum::AppTokenInvalidIssuer              => 'Invalid Token [Issuer]',
            HttpCodesEnum::AppTokenInvalidStructure           => 'Invalid Token [Token structure]',
            HttpCodesEnum::AppTokenInvalidTenant              => 'Invalid Token [Tenant]',
            HttpCodesEnum::AppTokenInvalidUser                => 'Invalid Token [User]',
            HttpCodesEnum::AppTokenNotPresent                 => 'Invalid Token [Token not present]',
            HttpCodesEnum::AppTokenNotValid                   => 'Invalid Token [verification - Token not valid]',
            HttpCodesEnum::AppTokenSignatureNotValid          => 'Invalid Token [verification - Signature not valid]',
            HttpCodesEnum::AppTokenUnsupportedHeaderFound     => 'Invalid Token [Unsupported header]',
            HttpCodesEnum::AppValidationFailed                => 'Validation error [%s]',
        };
    }
}
